services:
  app:
    build: .
    container_name: merch_shop
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Moscow"
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      LOGGER_FILE: ${LOGGER_FILE}
    volumes:
      - ./.env:/app/.env
    command: [ "./merchshop" ]


  migrate:
    image: migrate/migrate
    container_name: merch_shop_migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
      - "up"
    environment:
      TZ: "Europe/Moscow"
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
      WAIT_TIMEOUT: 30
    restart: "no"

  db:
    image: postgres:15-alpine
    container_name: merch_shop_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  pgdata: